-- MySQL Script generated by MySQL Workbench
-- 12/25/18 20:30:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rest_cafe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rest_cafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rest_cafe` DEFAULT CHARACTER SET utf8 ;
USE `rest_cafe` ;

-- -----------------------------------------------------
-- Table `rest_cafe`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rest_cafe`.`product` ;

CREATE TABLE IF NOT EXISTS `rest_cafe`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(45) NOT NULL,
  `productPrice` DOUBLE NOT NULL,
  `productType` VARCHAR(45) NULL DEFAULT NULL,
  `productSubType` VARCHAR(45) NULL DEFAULT NULL,
  `productSize` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rest_cafe`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rest_cafe`.`order` ;

CREATE TABLE IF NOT EXISTS `rest_cafe`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderNum` INT NOT NULL,
  `orderProduct` VARCHAR(45) NOT NULL,
  `orderCount` INT NOT NULL,
  `orderPrice` DOUBLE NOT NULL,
  `orderDate` VARCHAR(100) NOT NULL,
  `orderTotal` DOUBLE NULL DEFAULT NULL,
  `orderNote` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rest_cafe`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rest_cafe`.`user` ;

CREATE TABLE IF NOT EXISTS `rest_cafe`.`user` (
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
