-- MySQL Script generated by MySQL Workbench
-- 12/21/18 15:44:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema rest_cafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rest_cafe` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rest_cafe` ;

-- -----------------------------------------------------
-- Table `rest_cafe`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest_cafe`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(45) NOT NULL,
  `productPrice` DOUBLE NOT NULL,
  `productType` VARCHAR(45) NULL,
  `productSubType` VARCHAR(45) NULL,
  `productSize` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `rest_cafe`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest_cafe`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userPass` VARCHAR(45) NULL,
  `userPhoneNum` VARCHAR(45) NULL,
  `userAddress` VARCHAR(45) NULL,
  `userNational_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `rest_cafe`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest_cafe`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderNum` INT NOT NULL,
  `orderProduct` VARCHAR(45) NOT NULL,
  `orderCount` INT NOT NULL,
  `orderPrice` DOUBLE NOT NULL,
  `orderDate` varchar(100) NOT NULL,
  `orderTotal` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
