/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIForms;

import Classes.ImportantClass;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Adel Amer
 */
public class Orders extends javax.swing.JFrame {
    
    private final ImportantClass IC = ImportantClass.getInstance();
    public String Num1;
    private DefaultTableModel dtm;
    public Orders() {
        // Check Conection to DB
        if (!IC.dbc.check) {
            IC.dbc.ConnectDB();
        }
        initComponents();
        DateCombo.setDateFormat(DateFormat.getDateTimeInstance(2, 2));
        setLocationRelativeTo(null);
        ordersTable.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 11));
        ordersTable.getTableHeader().setAlignmentY(CENTER_ALIGNMENT);
        ordersTable.setAutoCreateColumnsFromModel(false);
        dtm = (DefaultTableModel) ordersTable.getModel();
    }
public void tabel1() {

        try { 
            String query = "SELECT   id,orderTotal,orderDate,orderPrice,orderCount,orderProduct,orderNum FROM order WHERE orderNum = '" + Search.getText() + "'";
            IC.pst = IC.dbc.conn.prepareStatement(query);
            IC.rs = IC.pst.executeQuery();
            if (IC.rs == null) {
                JOptionPane.showMessageDialog(rootPane, "البيانات غير موجود");
            }
            ordersTable.setModel(DbUtils.resultSetToTableModel(IC.rs));
        } catch (Exception s) {
            s.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PeacesNO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DateCombo = new datechooser.beans.DateChooserCombo();
        Search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        isertBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        billNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("إدارة بيانات الطلبات");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("إدارة بيانات الطلبات");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("عدد القطع:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("حساب القطعه:");

        PeacesNO.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PeacesNO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PeacesNO.setToolTipText("");
        PeacesNO.setName("name"); // NOI18N
        PeacesNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeacesNOActionPerformed(evt);
            }
        });
        PeacesNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PeacesNOKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PeacesNOKeyTyped(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("رقم الفاتورة:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("اسم المنتج:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("التاريخ:");

        DateCombo.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    DateCombo.setCalendarBackground(new java.awt.Color(255, 0, 0));
    DateCombo.setLocale(new java.util.Locale("ar", "AE", ""));

    Search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    Search.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    Search.setToolTipText("");
    Search.setName("Num"); // NOI18N
    Search.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            SearchActionPerformed(evt);
        }
    });
    Search.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            SearchKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            SearchKeyTyped(evt);
        }
    });

    jLabel8.setBackground(new java.awt.Color(204, 204, 204));
    jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 0, 0));
    jLabel8.setText("بحث:");

    searchBtn.setBackground(new java.awt.Color(255, 0, 0));
    searchBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
    searchBtn.setForeground(new java.awt.Color(255, 255, 255));
    searchBtn.setText("بحث");
    searchBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchBtnActionPerformed(evt);
        }
    });

    printBtn.setBackground(new java.awt.Color(255, 0, 0));
    printBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
    printBtn.setForeground(new java.awt.Color(255, 255, 255));
    printBtn.setText("طباعة");
    printBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            printBtnActionPerformed(evt);
        }
    });

    updateBtn.setBackground(new java.awt.Color(255, 0, 0));
    updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
    updateBtn.setForeground(new java.awt.Color(255, 255, 255));
    updateBtn.setText("تعديل");
    updateBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            updateBtnActionPerformed(evt);
        }
    });

    deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
    deleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
    deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
    deleteBtn.setText("حذف");
    deleteBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            deleteBtnActionPerformed(evt);
        }
    });

    isertBtn.setBackground(new java.awt.Color(255, 0, 0));
    isertBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
    isertBtn.setForeground(new java.awt.Color(255, 255, 255));
    isertBtn.setText("إضافة");
    isertBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            isertBtnActionPerformed(evt);
        }
    });

    ordersTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "م", "المجموع", "التاريخ", "سعر القطعة", "عدد القطع", "المنتج", "رقم الفاتورة"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    ordersTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            ordersTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(ordersTable);
    if (ordersTable.getColumnModel().getColumnCount() > 0) {
        ordersTable.getColumnModel().getColumn(0).setMinWidth(1);
        ordersTable.getColumnModel().getColumn(0).setPreferredWidth(1);
        ordersTable.getColumnModel().getColumn(0).setMaxWidth(1);
    }

    backBtn.setBackground(new java.awt.Color(0, 0, 0));
    backBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    backBtn.setForeground(new java.awt.Color(255, 255, 255));
    backBtn.setText("رجوع");
    backBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backBtnActionPerformed(evt);
        }
    });

    price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    price.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    price.setToolTipText("");
    price.setName("Num"); // NOI18N
    price.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            priceActionPerformed(evt);
        }
    });
    price.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            priceKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            priceKeyTyped(evt);
        }
    });

    name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    name.setToolTipText("");
    name.setName("Num"); // NOI18N
    name.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nameActionPerformed(evt);
        }
    });
    name.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            nameKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            nameKeyTyped(evt);
        }
    });

    billNum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    billNum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    billNum.setToolTipText("");
    billNum.setName("Num"); // NOI18N
    billNum.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            billNumActionPerformed(evt);
        }
    });
    billNum.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            billNumKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            billNumKeyTyped(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(400, 400, 400)
            .addComponent(jLabel1)
            .addGap(400, 400, 400))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(searchBtn)
                    .addGap(18, 18, 18)
                    .addComponent(Search)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8)
                    .addGap(443, 443, 443))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(billNum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(backBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(printBtn)
                        .addComponent(isertBtn)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PeacesNO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3)))
            .addGap(20, 20, 20))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel8)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchBtn)
                .addComponent(billNum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PeacesNO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(isertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(78, 78, 78)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PeacesNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeacesNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PeacesNOActionPerformed

    private void PeacesNOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PeacesNOKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PeacesNOKeyPressed

    private void PeacesNOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PeacesNOKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_PeacesNOKeyTyped

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchKeyPressed

    private void SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchKeyTyped

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    tabel1();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
         try {
            ordersTable.print();
        } catch (PrinterException ex) {
            Logger.getLogger(products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            double tot=Double.parseDouble(PeacesNO.getText())*Double.parseDouble(price.getText());
            String query = "UPDATE order SET orderNum=?, orderProduct=?, orderCount=?,orderPrice=?,orderDate=?,orderTotal=? WHERE id='" + Num1 + "' ";
            IC.pst = IC.dbc.conn.prepareStatement(query);
            IC.pst.setString(1, billNum.getText());
            IC.pst.setString(2, name.getText());
            IC.pst.setDouble(3, Double.parseDouble(PeacesNO.getText()));
            IC.pst.setDouble(4, Double.parseDouble(price.getText()));
            IC.pst.setString(5, DateCombo.getText());
            IC.pst.setDouble(6, tot);
            IC.pst.executeUpdate();
            name.setText("");
            price.setText("");
            PeacesNO.setText("");
            billNum.setText("");
            DateCombo.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ادخل بيانات صحيحه");
        }
        tabel1();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int p = JOptionPane.showConfirmDialog(null, " هل تريد حذفه؟", "حذف", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                String query = "DELETE FROM order WHERE id='" + Num1 + "' ";
                IC.pst = IC.dbc.conn.prepareStatement(query);
                IC.pst.executeUpdate();
            name.setText("");
            price.setText("");
            PeacesNO.setText("");
            billNum.setText("");
            DateCombo.setText("");
                JOptionPane.showMessageDialog(null, " تم الحذف");
            } catch (SQLException | HeadlessException e) {
            }
        }
        tabel1();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void isertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isertBtnActionPerformed
        try {
            double tot=Double.parseDouble(PeacesNO.getText())*Double.parseDouble(price.getText());
            String query = "INSERT INTO order (orderNum, orderProduct, orderCount,orderPrice,orderDate,orderTotal) VALUES (?, ?, ?, ?, ?, ?); ";
            IC.pst = IC.dbc.conn.prepareStatement(query);
            IC.pst.setString(1, billNum.getText());
            IC.pst.setString(2, name.getText());
            IC.pst.setDouble(3, Double.parseDouble(PeacesNO.getText()));
            IC.pst.setDouble(4, Double.parseDouble(price.getText()));
            IC.pst.setString(5, DateCombo.getText());
            IC.pst.setDouble(6, tot);
            IC.pst.executeUpdate();
            name.setText("");
            price.setText("");
            PeacesNO.setText("");
            billNum.setText("");
            DateCombo.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ادخل بيانات صحيحه");
        }
        tabel1();
    }//GEN-LAST:event_isertBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceKeyPressed

    private void priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_priceKeyTyped

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyPressed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyTyped

    private void ordersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersTableMouseClicked
        try {
            int row = ordersTable.getSelectedRow();
            Num1 = (ordersTable.getModel().getValueAt(row, 0).toString());
            String query = "SELECT * FROM order WHERE id='" + Num1 + "'";
            IC.pst = IC.dbc.conn.prepareStatement(query);
            IC.rs = IC.pst.executeQuery();
            if (IC.rs.next()) {
                String add1 = IC.rs.getString("orderProduct");
                name.setText(add1);
                String add2 = IC.rs.getString("orderPrice");
                price.setText(add2);
                String add4 = IC.rs.getString("orderCount");
                PeacesNO.setText(add4);
                String add5 = IC.rs.getString("orderNum");
                billNum.setText(add5);
                String add6 = IC.rs.getString("orderDate");
                DateCombo.setText(add6);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_ordersTableMouseClicked

    private void billNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billNumActionPerformed

    private void billNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billNumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_billNumKeyPressed

    private void billNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billNumKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_billNumKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo DateCombo;
    private javax.swing.JTextField PeacesNO;
    private javax.swing.JTextField Search;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField billNum;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton isertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTable ordersTable;
    private javax.swing.JTextField price;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
